const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]);scripts.forEach(s=>new vm.Script(s));
const elements=new Map();const context={window:{},URLSearchParams,location:{hash:'#profession=剑士&rank=3'},localStorage:{getItem:()=>null},document:{getElementById:id=>{if(!elements.has(id))elements.set(id,{value:''});return elements.get(id)}}};vm.createContext(context);vm.runInContext(scripts[0],context);
let app=scripts[1].replace(/    \$\('itemCount'\)[\s\S]*$/,'renderIdentity=()=>{};renderCard=()=>{};renderResults=()=>{};globalThis.test={clearSelectedEquipment,equipped,renderAccessoryAdvice,applyAccessoryPair,renderGem,catalog,professions,state,slots,gems,selectProfessionDefaults,slotItems,capFor,gemSwitchLevel,sanitize};})();');
vm.runInContext(app,context);const t=context.test;for(const slot of t.slots)t.state.filters[slot.id]={attributes:[],positiveOnly:true,matchAll:true};
assert.equal(t.catalog.length,new Set(t.catalog.map(i=>i.id)).size);assert(t.catalog.every(i=>i.level<=10&&i.servers.length===1&&i.servers[0]==='nostalgia'));assert.equal(t.professions.length,40);assert(t.professions.every(p=>Object.values(p.limits).every(v=>v.length===4)));assert(t.professions.some(p=>p.name==='游侠'));assert(!t.professions.some(p=>['舞者','仙人','侦探','教团骑士','暗黑骑士'].includes(p.name)));
const mur=t.catalog.find(i=>i.name==='村正');assert(mur.detailNote.includes('奥义·连击耗魔减少100%'));assert(mur.detailNote.includes('名匠锻造的刀'));assert(!mur.detailNote.includes('时/道'));assert.equal(mur.stats.attack.max,240);
assert.equal(t.catalog.filter(i=>i.level===9&&i.serverSources?.nostalgia?.includes('910733e7')).length,15);
assert(t.catalog.every(i=>!(/时\/道|时长|道具服|时道/.test(i.detailNote||''))));
assert(!html.includes('id="server"'));assert(!html.includes("$('server')"));assert(!html.includes('服务器规则'));for(const p of t.professions){t.state.loadout={weapon:t.catalog[0].id,accessory1:t.catalog.find(i=>i.category==='首饰').id};t.state.profession=p.id;t.selectProfessionDefaults();assert(t.slots.every(slot=>!t.state.loadout[slot.id]));for(const slot of t.slots.filter(s=>!s.accessory)){const selected=t.catalog.find(i=>i.id===t.state.loadout[slot.id]);if(selected){assert(selected.level<=t.capFor(selected.subtype));assert.equal(selected.level,Math.max(...t.slotItems(slot).map(i=>i.level)));}if(slot.id!=='offhand')assert.equal(t.capFor(t.state.types[slot.id]),Math.max(0,...slot.types.map(type=>t.capFor(type))));}const weapon=t.catalog.find(i=>i.id===t.state.loadout.weapon);if(weapon?.hands===2||['弓类','回力镖'].includes(t.state.types.weapon))assert(!t.state.loadout.offhand);}
t.state.profession=t.professions.find(p=>p.name==='剑士').id;t.selectProfessionDefaults();assert.equal(t.state.types.head,'头盔');assert.equal(t.state.types.body,'铠甲');assert.equal(t.state.types.feet,'靴子');assert.equal(t.state.types.weapon,'剑类');assert.equal(t.state.types.offhand,'盾牌');
assert.equal(t.gemSwitchLevel(t.gems.ruby.levels),10);assert.equal(t.gemSwitchLevel(t.gems.ruby.levels,7),7);assert.equal(t.gemSwitchLevel(t.gems.oceanHeart.levels,7),8);assert.equal(t.gemSwitchLevel(t.gems.oceanHeart.levels,10),10);assert.equal(t.gemSwitchLevel(t.gems.blackDragon.levels,1),10);assert.equal(t.gemSwitchLevel([],7),7);
for(const hash of ['#profession=不存在&rank=99','#profession=盗贼（游侠）&rank=2','#profession=剑士&rank=0']){const c={...context,window:{},location:{hash}};vm.createContext(c);vm.runInContext(scripts[0],c);vm.runInContext(app,c);assert(c.test.state.rank>=0&&c.test.state.rank<4);assert(c.test.professions.some(p=>p.id===c.test.state.profession));}
const box={hidden:false,innerHTML:'',querySelectorAll(selector){const key=selector==='[data-gem]'?'gem':'level';this.cache??={};const cacheKey=selector+this.innerHTML;if(this.cache[cacheKey])return this.cache[cacheKey];return this.cache[cacheKey]=[...this.innerHTML.matchAll(new RegExp('data-'+key+'="([^"]+)"','g'))].map(m=>({dataset:{[key]:m[1]},addEventListener(event,fn){this.click=fn}}));}};elements.set('gem-weapon',box);const slot=t.slots[0],item=t.slotItems(slot)[0];function click(key,value){t.renderGem(slot,item);box.querySelectorAll('[data-'+key+']').find(b=>b.dataset[key]===value).click();}click('gem','ruby');assert.equal(t.state.gems.weapon.level,10);click('level','7');click('gem','oceanHeart');assert.equal(t.state.gems.weapon.level,8);click('gem','ruby');assert.equal(t.state.gems.weapon.level,7);click('level','1');click('gem','blackDragon');assert.equal(t.state.gems.weapon.level,10);click('gem','ruby');assert.equal(t.state.gems.weapon.level,1);
const advice={textContent:'',innerHTML:'',querySelectorAll:()=>[]};elements.set('accessoryAdvice',advice);t.selectProfessionDefaults();t.renderAccessoryAdvice();assert(advice.textContent.includes('未选择饰品'));assert(!advice.innerHTML);assert(!t.state.loadout.accessory1&&!t.state.loadout.accessory2);t.applyAccessoryPair();assert.equal(t.state.lastAppliedAccessoryIds.length,2);for(const id of t.state.lastAppliedAccessoryIds){const selected=t.catalog.find(i=>i.id===id);assert(advice.innerHTML.includes(selected.name));}assert.equal(t.state.loadout.accessory1,t.state.lastAppliedAccessoryIds[0]);assert.equal(t.state.loadout.accessory2,t.state.lastAppliedAccessoryIds[1]);t.state.profession=t.professions.find(p=>p.name==='弓箭手').id;t.selectProfessionDefaults();t.renderAccessoryAdvice();assert(advice.textContent.includes('未选择饰品'));assert(t.slots.every(s=>!t.state.loadout[s.id]));assert(html.includes('minmax(280px,1fr)'));assert(!html.includes('身份与服务器'));
t.state.profession=t.professions.find(p=>p.name==='剑士').id;t.selectProfessionDefaults();t.state.loadout.weapon=t.slotItems(t.slots[0])[0].id;t.applyAccessoryPair();const savedWeapon=t.state.loadout.weapon;const savedTypes=JSON.stringify(t.state.types),savedGems=JSON.stringify(t.state.gems);t.clearSelectedEquipment(true);assert.equal(t.state.loadout.weapon,savedWeapon);assert(!t.state.loadout.accessory1&&!t.state.loadout.accessory2);assert.equal(t.state.lastAppliedAccessoryIds.length,0);assert(advice.textContent.includes('未选择饰品'));t.applyAccessoryPair();t.clearSelectedEquipment();assert(t.slots.every(s=>!t.state.loadout[s.id]));assert.equal(t.equipped().length,0);assert.equal(JSON.stringify(t.state.types),savedTypes);assert.equal(JSON.stringify(t.state.gems),savedGems);assert(advice.textContent.includes('未选择饰品'));t.clearSelectedEquipment();assert.equal(t.equipped().length,0);assert(html.includes('id="clearAllEquipment"'));assert(html.includes('id="clearAccessories"'));
console.log('PASS: 内联脚本、986装备/唯一ID/来源服别、40职业、15件9C、村正分段、全部职业装备未选中/最高上限类型、宝石等级及URL回退');
